apiVersion: v1
kind: Service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
metadata:
  name: gateway-service
  labels:
    name: gateway-service
    app: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: tcp-80
      nodePort: 30010
    - port: 443
      targetPort: 443
      name: tcp-443
      nodePort: 30011
  selector:
     app: gateway
     type: microservice
