apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    type: database
spec:
  containers:
    - name: mongo-pod
      image: mongo:4.2.12
      command:
      - /bin/bash
      - -c
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "vaxidrez"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "$VaxiDrez2025"
      ports:
        - containerPort: 27017